### ISSUE TITLE
데이터를 통신하는데에 있어서 오류가 발생합니다.

### ISSUE THREAD

**Issue by Zero-1016** [KIT-Frontend-Team2/week14-pair1-IfProfject#7]
Failed to execute 'text' on 'Response': body stream already read
TypeError: Failed to execute 'text' on 'Response': body stream already read
    at serializeResponse (http://localhost:3000/static/js/bundle.js:43775:27)
    at Emitter.<anonymous> (http://localhost:3000/static/js/bundle.js:43809:48)
    at Emitter.onceListener (http://localhost:3000/static/js/bundle.js:81505:16)
    at http://localhost:3000/static/js/bundle.js:81543:16
    at Array.forEach (<anonymous>)
    at Emitter.emit (http://localhost:3000/static/js/bundle.js:81542:15)
    at source.emit (http://localhost:3000/static/js/bundle.js:44152:20)
    at http://localhost:3000/static/js/bundle.js:43900:23
    at ServiceWorkerContainer.<anonymous> (http://localhost:3000/static/js/bundle.js:44252:15)

같은 페이지 내에서? 거의 동시에 API 호출을 두 번 이상 시도할 시? 생기는 문제인거 같습니다. 개발을 하는데에 있어서 큰 문제는 없었지만 문제점을 찾고있습니다.

![image](https://github.com/KIT-Frontend-Team2/week14-pair1-IfProfject/assets/115636461/6c16eaa6-4812-4856-a5a6-6a6b3ab78e14)

**Comment by Zero-1016** [comment]
MSW 문제였던거 같습니다 실제 비동기 통신시 문제가 되지 않습니다!
